### ISSUE TITLE
Python-Poetry cheatsheet 

### ISSUE THREAD

**Issue by prakashjayy** [prakashjayy/fullstack_dl#17]
Poetry helps you declare, manage and install dependencies of Python projects, ensuring you have the right stack everywhere.
- [web url](https://python-poetry.org/)
- [github](https://github.com/python-poetry/poetry)
- [stackoverflow](https://stackoverflow.com/questions/tagged/python-poetry)

I have been using poetry for a year now. since 1.0 version released a few months back, it is safe to use and expect it to be stable.

## install
```bash
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
```

```
$ export PATH="/Users/vanapalliprakash/Library/Python/3.9/bin:$PATH"               
$ poetry --version
> Poetry version 1.1.7
```

if it prompts to install virtualenv, do 

```bash
python3 -m pip install virtualenv
```

## useful commands
- `poetry init` to initalize a poetry project.
- `poetry install` to install the environment. upon installing, `poetry.lock` file is created  
- `poetry update` to update the enviroment
- `poetry show --tree` to have an insight of your project's dependencies.
- `poetry build` create a package
- `poetry publish` publish pip package
- `poetry env info` to check virtualenv info and system info used by poetry. we get python path here which can be pasted to vscode python path.

## pyproject.toml
repos using poetry contains `pyproject.toml` which contains all the info about package.  do `poetry init` and we get a toml file as mentioned below along with a bunch of other files.

```toml
[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["prakashjayy <vanapaliprakash@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Adding dependencies to `toml` file 
- when u want to add a package with optional dependencies or features, `poetry add typer"[all]"` or add `typer = {extras = ["all"], version = "^0.3.2"}`
